algorithm
Anastasiya-Shir/JS_Object pull request #2
Opened 2022-05-07 16:53 UTC by Anastasiya-Shir

2022-05-13 20:30 UTC, kathrynowy requested changes

2022-05-13 20:30 UTC, kathrynowy commented on index.alg.html
> +  <script src="./indexlAlg.js"></script>
называем просто index

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// let isNumberEqual = (a, b) => return (a === b);
зачем скобки (a === b)? 
запусти
функция не работает

если на работе запушишь неработающее - получишь трындюлей)

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return a + b > 10;
переписать на стрелочную

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// let isNumberNegative = (n) => n < 0;
```suggestion
// let isNumberNegative = n => n < 0;
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     str = str.concat('x');
```suggestion
//     str += 'x';
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//       str = str.concat(i);
тоже самое

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// alert(together.concat(letters, lettersSecond));
переписать с использованием деструктуризации

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// mas.push(1, 2, 3);
переписать с использованием деструктуризации

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// str = mas.join("");
переписать в одну строчку без переменной mas

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// let check = str.indexOf('http://');
использовать метод строк который проверяет начало

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
в твоей реализации переписать в одну строку с использованием одного document.write

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   document.write("no");
тоже самое

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   document.write("no");
так же попробовать find()
и в одну строчку решение

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     if (num % i == 0) {
```suggestion
//     if (num % i === 0) {
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     if (num % i == 0) {
и вообще переписать без === 0

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// getDevisor(8);
devisor ??

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// (function getMassiv() {
massiv? что за транслит)

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return k;
```suggestion
//   for (let i = 1; i < 6; i++) {
//     let str = '';

//     for (let j = 1; j <= i; j++) {
//       str = str.concat(i);
//     }

//     mas.push(str);
//   }

//   console.log(mas);

//   return mas;
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return k;
посмотри исправленный вариант
что за 
let k = console.log(mas);

   return k; 
??

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return k;
и что за переменная mas

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     newArray = newArray.concat([array[i]])
используй push , усложнено

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
переписать в 1 строчку

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   console.log(prev)
зачем клг пушишь?

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// const fromPairs = (array) => array.reduce((prev, item) => {
```suggestion
// const fromPairs = array => array.reduce((prev, item) => {
```

когда 1 параметр, скобки не нужны

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
```suggestion
// const without = (array, ...args) => {
//   let newArray = array;

//   for (let i = 0; i < args.length; i++) {
//     array = array.filter((el) => el !== args[i]);
//   }

//   return array;
// }
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
очень тяжело читать код, разделяй

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return Array.from(new Set(newarray));
зачем переменная newarray??
убери явный ретурн

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   if (firstArray.length != secondArray.length) return false;
убрать  false

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   if (firstArray.length != secondArray.length) return false;
```suggestion
//   if (firstArray.length !== secondArray.length) return false;
```
!!!!!!!

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     else return true;
избавиться от return true false
переписать без.if 
c одним ретурном и в одну строчку  и без true/false

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +
не нужна пустая строка здесь

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
переписать на стрелочную в одну строчку без if

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
и без true/false

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// }
переписать на fiter в одну строчку

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     sum += Number(str[i]);
```suggestion
//     sum += +str[i];
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +// function ucfirst(str) {
функция ucfirst должна принимать 1 слово и делать заглавной букву только у него

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     newStr += zagFirst + next + ' ';
написать в одну строчку не через. substring (slice)

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     newStr += zagFirst + next + ' ';
используя не for,  а метод для массива (который меняет исходный массив и проходится по нему)

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//     newStr += zagFirst + next + ' ';
и в одну строчку

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return newarray;
если ты меняешь переменную вне функции - ее не нужно возвращать
поэтому создай переменную внутри функции

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +//   return newarray;
и убрать все консоли

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +      num += Number(str[i]);
```suggestion
      num += +str[i];
```

2022-05-13 20:30 UTC, kathrynowy commented on indexlAlg.js
> +  throw Error("input only number");
почему всегда ошибка будет выдаваться? условие задай

2022-05-15 08:17 UTC, Anastasiya-Shir commented on indexlAlg.js
> +//   return newarray;
Создала переменную для перезаписи, не знаю возможно не совсем правильно поняла

2022-05-15 08:38 UTC, Anastasiya-Shir commented on indexlAlg.js
> +//     newStr += zagFirst + next + ' ';
Исправила, но возможно не совсем так как нужно, нужно пояснения, если не так поняла

2022-05-18 21:16 UTC, kathrynowy requested changes

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//     if (num % i == 0) {
строгое сравнение

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//   if (firstArray.length != secondArray.length) return false;
сравнение

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//     if (firstArray[i] != secondArray[i]) return false;
сравнение

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//     else return true;
написать один ретурн с ? :

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//     return false;
переписать

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +// const getStringWithUPFirstLetter = str => str.split(' ').map(item => ucfirst(item)).join(' ');
```suggestion
// const getStringWithUPFirstLetter = str => str.split(' ').map(ucfirst).join(' ');
```

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +// }
```suggestion
// function getSum(num) {
   if (typeof (num) !== Number) {
     throw Error("input only number");
   }

//   if (num <= 9) {
//     return num;
//   }

     str = String(num);
     num = 0;

     for (let i = 0; i < str.length; i++) {
       num += +(str[i]);
     }

     return getSum(num);
   }
 }
```

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +// }
мы сразу пишем условия для выхода
потом логику

тем самым избавились от вложенности if else

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//   } else if (typeof (num) != Number) {
строгое сравнение

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//     throw Error("input only number");
throw new Error
проверяй всю функцию

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//         arr[i + 1] = firsElem;
переписать с помощью деструктуризации в одну строку
 без доп переменных

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//         arr[i + 1] = firsElem;
переписать с помощью деструктуризации в одну строку
без доп переменных

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +let countleft = 0;
```suggestion
let countLeft = 0;
```

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +  if (array.length === 2 && array[0] != someNumber && array[1] != someNumber) {
строгое сравнение!!!

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +    return ("we don't have this number");
there is no such number

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//   }
```suggestion
//     return arr.length === a ? arr[arr.length - 1] :  fib(a);
```

2022-05-18 21:16 UTC, kathrynowy commented on algorithm/index.js
> +//   })
```suggestion
//   let arg = args.flat().sort((a, b) =>  a - b);
```

2022-05-23 20:48 UTC, kathrynowy requested changes

2022-05-23 20:48 UTC, kathrynowy commented on algorithm/index.js
> +  //   let arg = args.flat().sort((a, b) => a - b);
why do u need sort here?

2022-05-23 20:48 UTC, kathrynowy commented on algorithm/index.js
> +  //   for (let i = 0; i < string; i++) {
why do u write 4 loops?
log matrix in the first loops

2022-05-23 20:48 UTC, kathrynowy commented on algorithm/index.js
> +  //   if (a < 2 || typeof a != Number) {
сравнение строгое!!!

2022-05-25 11:39 UTC, Anastasiya-Shir commented on algorithm/index.js
> +  //   let arg = args.flat().sort((a, b) => a - b);
because i I wanted to solve the problem in a different way, I forgot to remove the excess. Сorrected it

2022-06-03 05:49 UTC, merged